### ISSUE TITLE
Should schemas match REST API docs or ACTUAL responses from ArcGIS Online?

### ISSUE THREAD

**Issue by amarinelli** [AmrEldib/agol-schemas#16]
Example:

**Response Properties** on [Group](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Group/02r30000006m000000/) operation doc page does not match actual response from ArcGIS Online.

``` javascript
{
  "id": "401d8533ae9849cc87f5a07a0f6399ac",
  "title": "amarinelli",
  "isInvitationOnly": true,
  "owner": "amarinelli",
  "description": "This group should remain PUBLIC for testing.  Do not delete.",
  "snippet": "This group should remain PUBLIC for testing.  Do not delete.",
  "tags": [
    "group",
    "testing"
  ],
  "phone": "",
  "sortField": "title",
  "sortOrder": "asc",
  "isViewOnly": true,
  "isFav": false,
  "thumbnail": "esri-64.png",
  "created": 1421252352000,
  "modified": 1459538737000,
  "provider": null,
  "providerGroupName": null,
  "isReadOnly": false,
  "access": "public",
  "capabilities": [

  ]
}
```

See #15 for other examples of this.  Should the schema's match what the docs say or what the actual response returns?  Thoughts @AmrEldib?

**Comment by AmrEldib** [comment]
It should match actual responses, not the documentation.
However, it's harder to figure this out unless we test everything.
So, for now, we'll follow the documentation, and as we discover errors we correct the schema, and inform Esri to correct their documentation. Issue #15 will contain all errors
The problem with matching actual responses is that we'll have only one (or few) examples. This is fine if the response is simple. But for more complex response, there's a chance for errors. We need to be careful when changing the schemas based on few examples.
